import PeopleIcon from "@mui/icons-material/People";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import { Icon } from "@iconify/react";
import { ROLES } from "./ConstantRoles";

const MENU_CONFIG = [
  {
    label: "Dashboard",
    value: "dashboard",
    icon: <Icon icon="svg-spinners:blocks-scale" fontSize="20px" />,
    roles: [
      ROLES.SUPERADMIN,
      ROLES.DIVISI_KONTRAK,
      ROLES.KEPALA_SEKSI,
      ROLES.KEPALA_SUBDIVISI,
      ROLES.KEPALA_DIVISI,
      ROLES.DIREKTUR_BISNIS,
      ROLES.DIREKTUR_UTAMA,
      ROLES.DIVISI_KEUANGAN,
      ROLES.ADMIN_IZIN_LAHAN,
    ],
    submenu: [
      {
        label: "Sewa Ruangan",
        value: "dashboard",
        path: "/dashboard",
        icon: <Icon icon="solar:shop-2-bold-duotone" fontSize="20px" />,
        showIcon: true,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.DIVISI_KONTRAK,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
          ROLES.DIVISI_KEUANGAN,
        ],
      },
      {
        label: "Izin Lahan",
        value: "land-permit-dashboard",
        path: "/land-permit-dashboard",
        icon: <Icon icon="healthicons:market-stall" fontSize="20px" />,
        showIcon: true,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.ADMIN_IZIN_LAHAN,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
          ROLES.DIVISI_KEUANGAN,
        ],
      },
    ],
  },

  {
    label: "Data Master",
    value: "dataMaster",
    icon: <Icon icon="material-symbols:database" fontSize="20px" />,
    roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK, ROLES.ADMIN_IZIN_LAHAN],
    submenu: [
      {
        label: "Peran",
        value: "roles",
        path: "/roles",
        icon: <Icon icon="oui:app-users-roles" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN],
        showIcon: true,
      },
      {
        label: "Pengguna",
        value: "users",
        path: "/users",
        icon: <Icon icon="hugeicons:location-user-03" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN],
        showIcon: true,
      },
      {
        label: "Lokasi",
        value: "locations",
        path: "/locations",
        icon: <Icon icon="mdi:location-radius-outline" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK, ROLES.ADMIN_IZIN_LAHAN],
        showIcon: true,
      },
      {
        label: "Lantai",
        value: "floor",
        path: "/floor",
        icon: <Icon icon="ion:pricetags-outline" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK],
        showIcon: true,
      },
      {
        label: "Ruangan",
        value: "rooms",
        path: "/rooms",
        icon: <Icon icon="cil:room" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK],
        showIcon: true,
      },
      {
        label: "Sektor",
        value: "land-sectors",
        path: "/land-sectors",
        icon: (
          <Icon icon="solar:map-arrow-square-bold-duotone" fontSize="20px" />
        ),
        roles: [ROLES.SUPERADMIN, ROLES.ADMIN_IZIN_LAHAN],
        showIcon: true,
      },
      {
        label: "Lahan",
        value: "land-stalls",
        path: "/land-stalls",
        icon: <Icon icon="solar:shop-bold-duotone" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.ADMIN_IZIN_LAHAN],
        showIcon: true,
      },
      {
        label: "Daftar Identitas",
        value: "identity-lists",
        path: "/identity-lists",
        icon: <Icon icon="qlementine-icons:id-card-16" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK, ROLES.ADMIN_IZIN_LAHAN],
        showIcon: true,
      },
    ],
  },
  {
    label: "Transaksi",
    value: "transactions",
    icon: <Icon icon="healthicons:money-bag" fontSize={22} />,
    roles: [
      ROLES.SUPERADMIN,
      ROLES.DIVISI_KONTRAK,
      ROLES.KEPALA_SEKSI,
      ROLES.KEPALA_SUBDIVISI,
      ROLES.KEPALA_DIVISI,
      ROLES.DIREKTUR_BISNIS,
      ROLES.DIREKTUR_UTAMA,
      ROLES.DIVISI_KEUANGAN,
      ROLES.ADMIN_IZIN_LAHAN,
    ],
    submenu: [
      {
        label: "Permohonan Lahan",
        value: "land-permit-applications",
        path: "/land-permit-applications",
        icon: <Icon icon="solar:document-add-bold-duotone" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.ADMIN_IZIN_LAHAN],
        showIcon: true,
      },
      {
        label: "Permohonan Ruangan",
        value: "tenant-application",
        path: "/tenant-application",
        icon: <Icon icon="hugeicons:file-edit" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK],
        showIcon: true,
      },
      {
        label: "Persetujuan Ruangan",
        value: "tenant-approval",
        path: "/tenant-approval",
        icon: <Icon icon="carbon:document-set" fontSize="20px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
        ],
        showIcon: true,
      },
      {
        label: "Persetujuan Lahan",
        value: "land-permit-approval",
        path: "/land-permit-approval",
        icon: <Icon icon="ph:seal-check-duotone" fontSize="20px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
        ],
        showIcon: true,
      },
      {
        label: "Non-Aktif Ruangan",
        value: "tenant-terminations",
        path: "/tenant-terminations",
        icon: <Icon icon="pepicons-pop:lock-closed-circle" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK],
        showIcon: true,
      },
      {
        label: "Non-Aktif Izin Lahan",
        value: "land-permit-terminations",
        path: "/land-permit-terminations",
        icon: (
          <Icon
            icon="solar:lock-keyhole-minimalistic-bold-duotone"
            fontSize="20px"
          />
        ),
        roles: [ROLES.SUPERADMIN, ROLES.ADMIN_IZIN_LAHAN],
        showIcon: true,
      },
      {
        label: "Non-Aktif Ruangan",
        value: "tenant-terminations-approval",
        path: "/tenant-terminations-approval",
        icon: <Icon icon="pepicons-pop:lock-closed-circle" fontSize="20px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
        ],
        showIcon: true,
      },
      {
        label: "Non-Aktif Izin Lahan",
        value: "land-permit-termination-approval",
        path: "/land-permit-termination-approval",
        icon: (
          <Icon
            icon="solar:lock-keyhole-minimalistic-bold-duotone"
            fontSize="20px"
          />
        ),
        roles: [
          ROLES.SUPERADMIN,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
        ],
        showIcon: true,
      },
      {
        label: "Pembayaran Ruangan",
        value: "payments",
        path: "/payments",
        icon: (
          <Icon icon="streamline-freehand:money-atm-withdraw" fontSize="20px" />
        ),
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK, ROLES.DIVISI_KEUANGAN],
        showIcon: true,
      },
      {
        label: "Pembayaran Lahan",
        value: "land-permit-payments",
        path: "/land-permit-payments",
        icon: <Icon icon="solar:wallet-money-bold-duotone" fontSize="20px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.DIVISI_KEUANGAN,
          ROLES.ADMIN_IZIN_LAHAN,
        ],
        showIcon: true,
      },
      {
        label: "Buku Kontrak",
        value: "contracts",
        path: "/contracts",
        icon: <Icon icon="clarity:contract-line" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.DIVISI_KONTRAK],
        showIcon: true,
      },
      {
        label: "Dokumen Izin Lahan",
        value: "land-permit-documents",
        path: "/land-permit-documents",
        icon: <Icon icon="solar:document-text-bold-duotone" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN, ROLES.ADMIN_IZIN_LAHAN],
        showIcon: true,
      },
    ],
  },
  {
    label: "Laporan",
    value: "reports",
    icon: <Icon icon="fluent:chart-multiple-16-filled" fontSize={23} />,
    roles: [
      ROLES.SUPERADMIN,
      ROLES.DIVISI_KONTRAK,
      ROLES.KEPALA_SEKSI,
      ROLES.KEPALA_SUBDIVISI,
      ROLES.KEPALA_DIVISI,
      ROLES.DIREKTUR_BISNIS,
      ROLES.DIREKTUR_UTAMA,
      ROLES.DIVISI_KEUANGAN,
    ],
    submenu: [
      {
        label: "Laporan per Lokasi",
        value: "locations-report",
        path: "/locations-report",
        icon: <Icon icon="ant-design:pie-chart-filled" fontSize="20px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.DIVISI_KONTRAK,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
          ROLES.DIVISI_KEUANGAN,
        ],
        showIcon: true,
      },
      {
        label: "Laporan per Penyewa",
        value: "tenants-report",
        path: "/tenants-report",
        icon: <Icon icon="bi:bar-chart-fill" fontSize="18px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.DIVISI_KONTRAK,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
          ROLES.DIVISI_KEUANGAN,
        ],
        showIcon: true,
      },
      {
        label: "Jatuh Tempo",
        value: "payment-due-report",
        path: "/payment-due-report",
        icon: <Icon icon="solar:alarm-bold-duotone" fontSize="20px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.DIVISI_KONTRAK,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
          ROLES.DIVISI_KEUANGAN,
        ],
        showIcon: true,
      },
      {
        label: "Kontrak Segera Berakhir",
        value: "contract-expiry-report",
        path: "/contract-expiry-report",
        icon: <Icon icon="solar:calendar-mark-bold-duotone" fontSize="20px" />,
        roles: [
          ROLES.SUPERADMIN,
          ROLES.DIVISI_KONTRAK,
          ROLES.KEPALA_SEKSI,
          ROLES.KEPALA_SUBDIVISI,
          ROLES.KEPALA_DIVISI,
          ROLES.DIREKTUR_BISNIS,
          ROLES.DIREKTUR_UTAMA,
          ROLES.DIVISI_KEUANGAN,
        ],
        showIcon: true,
      },
      {
        label: "Log Sinkron Ruangan",
        value: "room-sync-logs",
        path: "/room-sync-logs",
        icon: <Icon icon="solar:refresh-circle-bold-duotone" fontSize="20px" />,
        roles: [ROLES.SUPERADMIN],
        showIcon: true,
      },
    ],
  },
  {
    label: "Pengaturan",
    value: "settings",
    icon: <Icon icon="line-md:cog-loop" fontSize={23} />,
    roles: Object.values(ROLES),
    hidden: true,
    submenu: [
      {
        label: "Akun",
        value: "account",
        path: "/account",
        icon: <Icon icon="mdi:account-edit" fontSize="20px" />,
        roles: Object.values(ROLES),
        hidden: true,
      },
    ],
  },
  // Tambahkan menu lain jika perlu
];

export default MENU_CONFIG;
